# Simple docs deployment which requires the docs be built locally and pushed to master.
# The workflow copies the entire ./docs directory over to git-pages branch.
# The key resources in ./docs are index.html and images/.
name: Docs Deployment
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: action information
        run: |
          whoami
          sudo chmod 777 --recursive /usr/local
      - name: install graphviz
        run: |
          sudo apt-get install graphviz
      - name: install asciidoctor
        run: |
          sudo apt-get install asciidoctor
          sudo gem install asciidoctor-tabs
          sudo gem install asciidoctor-diagram
      - uses: actions/checkout@v2
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs